name: wechat
description: im

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  extended_image: ^0.6.8
  shared_preferences: ^0.5.6
  bot_toast: ^2.2.0
  json_annotation: ^3.0.1
  dartin: ^0.1.5
  rxdart: ^0.23.1
  worker_manager: 2.1.6
  generic_json_converter_annotation: ^0.0.2
  chopper: ^3.0.1+1
  copy_with_extension: ^1.0.7
  websocket: ^0.0.5
  flutter_easyrefresh: ^2.0.8
  flutter_spinkit: ^4.1.1
  badges: ^1.1.0
  webview_flutter: ^0.3.19
  qr_flutter: ^3.2.0
  qrcode: ^1.0.4
  lpinyin: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  json_serializable: ^3.2.5
  generic_json_converter_generator: ^0.0.4
  chopper_generator:
    path: C:\Users\windr\AndroidStudioProjects\chopper\chopper_generator
  copy_with_extension_gen:
    path: C:\Users\windr\AndroidStudioProjects\copy_with_extension\copy_with_extension_gen

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png
    - assets/images/ic_new_friend.png
    - assets/images/ic_group_chat.png
    - assets/images/ic_chat_add.png
    - assets/images/ic_chat_emoji.png
    - assets/images/ic_chat_sound.png
    - assets/images/ic_chat_keyboard.png
    - assets/images/ic_voice.png
    - assets/images/ic_settings.png
    - assets/images/default_avatar.png
    - assets/images/ic_gallery.png
    - assets/images/logo.png
  fonts:
    - family: appIconFont
      fonts:
        - asset: assets/fonts/iconfont.ttf
